services:
  mi-aplicacion-spring:
    image: p6-1:latest
    ports:
      - "8080:8081"
    networks:
      - red-interna
    environment:
      - URL_SERVICIO=http://servicio-consumible:8081

  servicio-consumible:
    image: javillour/servicio-tt1:amd64
    networks:
      - red-interna

networks:
  red-interna:
    driver: bridge
